const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {DATA,analyseIssues}=require('./src/data');const {runAgent}=require('./src/agent');const {runOpenAIAgent}=require('./src/openai-agent');
const PORT=process.env.PORT||3000,pending=new Map(),stateFile=path.join(__dirname,'data','actions.json');
const load=()=>{try{return JSON.parse(fs.readFileSync(stateFile,'utf8'))}catch{return[]}};const save=x=>{fs.mkdirSync(path.dirname(stateFile),{recursive:true});fs.writeFileSync(stateFile,JSON.stringify(x,null,2))};
function send(res,s,d,t='application/json'){res.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store'});res.end(t.includes('json')?JSON.stringify(d):d)}
function parse(req){return new Promise((ok,bad)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(JSON.parse(d||'{}'))}catch(e){bad(e)}})})}
function user(req,b={}){let role=b.role||req.headers['x-role']||'customer',account=b.account||req.headers['x-account']||'ACCT-001';return{role:['customer','support','ops'].includes(role)?role:'customer',account:DATA.accounts[account]?account:'ACCT-001'}}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='GET'&&req.url==='/api/context')return send(res,200,{snapshot:DATA.snapshot,accounts:Object.entries(DATA.accounts).map(([id,a])=>({id,name:a.account_name}))});
 if(req.method==='POST'&&req.url==='/api/chat'){let b=await parse(req),u=user(req,b),message=String(b.message||'');if(process.env.OPENAI_API_KEY){try{return send(res,200,await runOpenAIAgent(message,u))}catch(e){return send(res,200,{...runAgent(message,u),framework:'Deterministic fallback',agentError:'LLM unavailable'})}}return send(res,200,{...runAgent(message,u),framework:'Deterministic fallback (set OPENAI_API_KEY to enable SDK agent)'})}
 if(req.method==='POST'&&req.url==='/api/issues'){let b=await parse(req),u=user(req,b);return u.role==='customer'?send(res,403,{error:'Operations access required'}):send(res,200,analyseIssues())}
 if(req.method==='POST'&&req.url==='/api/actions/prepare'){let b=await parse(req),u=user(req,b);if(!['escalation','ticket_update','follow_up'].includes(b.type)||(u.role==='customer'&&b.type!=='escalation'))return send(res,403,{error:'Not authorised'});let token=crypto.randomUUID(),item={type:b.type,summary:String(b.summary||'').slice(0,500),target:String(b.target||'').slice(0,50),role:u.role,account:u.account,preparedAt:new Date().toISOString()};pending.set(token,item);return send(res,200,{token,requiresConfirmation:true,preview:item})}
 if(req.method==='POST'&&req.url==='/api/actions/confirm'){let b=await parse(req),item=pending.get(b.token);if(!item)return send(res,404,{error:'Action expired'});if(b.confirm!==true)return send(res,400,{error:'Explicit confirmation required'});pending.delete(b.token);let x=load(),done={id:`ACT-${String(x.length+1).padStart(4,'0')}`,...item,status:'created',executedAt:new Date().toISOString()};x.push(done);save(x);return send(res,201,done)}
 let rel=req.url==='/'?'index.html':decodeURIComponent(req.url.split('?')[0].slice(1)),root=path.join(__dirname,'public'),file=path.resolve(root,rel);if(!file.startsWith(path.resolve(root)))return send(res,403,'Forbidden','text/plain');fs.readFile(file,(e,d)=>e?send(res,404,'Not found','text/plain'):send(res,200,d,file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'text/html'));
}catch(e){send(res,400,{error:e.message})}});if(require.main===module)server.listen(PORT,()=>console.log(`ParcelPilot: http://localhost:${PORT}`));module.exports={server};
