const {Agent,run,tool,setDefaultOpenAIClient,setOpenAIAPI,setTracingDisabled}=require('@openai/agents');const OpenAI=require('openai');const {z}=require('zod');const {DATA,searchDocuments,lookupOrder,lookupTicket,analyseIssues}=require('./data');const {runAgent}=require('./agent');
const openRouter=Boolean(process.env.OPENROUTER_API_KEY);if(openRouter){setDefaultOpenAIClient(new OpenAI({apiKey:process.env.OPENROUTER_API_KEY,baseURL:'https://openrouter.ai/api/v1',defaultHeaders:{'HTTP-Referer':process.env.APP_URL||'http://localhost:3000','X-OpenRouter-Title':'ParcelPilot Support Copilot'}}));setOpenAIAPI('chat_completions');if(setTracingDisabled)setTracingDisabled(true)}
const log=(ctx,name,label)=>ctx?.context?.trace.push({name,label,status:'complete'});
const documentSearch=tool({name:'document_search',description:'Search policies, SOPs, product documentation, and only agreements authorised for the user.',parameters:z.object({query:z.string()}),execute:({query},ctx)=>{log(ctx,'document_search','Agent searched authoritative documents');return searchDocuments(query,ctx.context.user).map(({filename,title,kind,authority,text})=>({filename,title,kind,authority,text}))}});
const structuredLookup=tool({name:'structured_lookup',description:'Look up one order or ticket. Account isolation is enforced inside this tool.',parameters:z.object({record_type:z.enum(['order','ticket']),record_id:z.string()}),execute:({record_type,record_id},ctx)=>{log(ctx,'structured_lookup',`Agent looked up ${record_id} with access controls`);return record_type==='order'?lookupOrder(record_id.toUpperCase(),ctx.context.user):lookupTicket(record_id.toUpperCase(),ctx.context.user)}});
const policyEngine=tool({name:'policy_calculation',description:'Deterministically evaluate cancellation, service-credit, SLA, and known-issue rules. Use for consequential conclusions.',parameters:z.object({question:z.string()}),execute:({question},ctx)=>{log(ctx,'policy_calculation','Agent applied deterministic policy controls');return runAgent(question,ctx.context.user)}});
const issueDetection=tool({name:'issue_detection',description:'Analyse internal tickets for P1 incidents, response-target breaches, and known-issue matches.',parameters:z.object({scope:z.string()}),isEnabled:({runContext})=>runContext.context.user.role!=='customer',execute:(_,ctx)=>{log(ctx,'issue_detection','Agent analysed proactive support risks');return analyseIssues()}});
const Output=z.object({answer:z.string(),confidence:z.enum(['high','medium','low']),source_filenames:z.array(z.string()),action_type:z.enum(['escalation','ticket_update','follow_up']).nullable(),action_summary:z.string().nullable(),action_target:z.string().nullable()});
const selectedModel=process.env.OPENROUTER_MODEL||process.env.OPENAI_MODEL||(openRouter?'openai/gpt-4.1-mini':'gpt-4.1-mini');const agent=new Agent({name:'ParcelPilot Support Agent',model:selectedModel,instructions:`Use only tool results. For order/ticket requests use structured_lookup, document_search, then policy_calculation. Never infer inaccessible data. Agreement > current SOP/policy > current product guide; deprecated and historical sources cannot control. Use the workbook snapshot for time. Never execute actions; only propose one for explicit confirmation. Escalate missing evidence or human judgment.`,tools:[documentSearch,structuredLookup,policyEngine,issueDetection],outputType:Output});
async function runOpenAIAgent(message,user){let trace=[],result=await run(agent,message,{context:{user,trace},maxTurns:8}),x=result.finalOutput,valid=new Set(DATA.documents.map(d=>d.filename)),sources=x.source_filenames.filter(f=>valid.has(f)).map(filename=>({title:filename,filename,authority:'agent-cited'})),response={answer:x.answer,confidence:x.confidence,tools:trace,sources,action:x.action_type?{type:x.action_type,summary:x.action_summary||'Review agent request',target:x.action_target||''}:undefined,framework:openRouter?'OpenAI Agents SDK via OpenRouter':'OpenAI Agents SDK',model:selectedModel};const verified=runAgent(message,user),mustVerify=/(?:ORD|TKT)-\d+|cancel|credit|late|delay|pickup|action|change|update|account|payment|upgrade/i.test(message)||verified.confidence==='low'||(user.role==='customer'&&response.action?.type!=='escalation');if(mustVerify)response={...response,answer:verified.answer,confidence:verified.confidence,sources:verified.sources,action:verified.action,conflicts:verified.conflicts,trust:verified.trust,tools:[...trace,{name:'safety_verification',label:'Verified access, evidence, policy precedence, and action permissions in code',status:'complete'}]};return response}module.exports={runOpenAIAgent,agent};
